name: Lint

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
  lint:
    name: Run Go Linter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
        
      # Step 3: Create a bin directory
      - name: Create bin directory
        run: mkdir -p $GITHUB_WORKSPACE/bin

      # Step 4: Add bin directory to PATH
      - name: Update PATH
        run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      # Step 5: Install golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.54.2

      # Step 6: Run golangci-lint
      - name: Run golangci-lint
        run: |
          golangci-lint run --timeout=5m
